# Generated by Django 3.0 on 2022-05-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=150)),
                ('mobile_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
