# Generated by Django 3.0 on 2022-05-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TENNIS_APP', '0002_auto_20220523_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinebooking',
            name='day',
        ),
        migrations.AddField(
            model_name='onlinebooking',
            name='date',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlinebooking',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
