# Generated by Django 3.0 on 2022-05-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TENNIS_APP', '0003_auto_20220523_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebooking',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onlinebooking',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
