# Generated by Django 3.0 on 2022-05-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TENNIS_APP', '0004_auto_20220523_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebooking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='onlinebooking',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
